export interface Metadata {
  title?: string;
  description?: string;
  keywords?: string;
  creator?: string;
  openGraph?: { title?: string; description?: string; type?: string };
  twitter?: { card?: string; title?: string; description?: string };
}

export interface Conversion {
  from: string;
  to: string;
  metadata: Metadata;
  type: 'image' | 'video' | 'audio' | 'document';
}

function generateMeta(from: string, to: string, _type: "image" | "video" | "audio" | "document"): Metadata {
  const desc = `Convert ${from} to ${to} in your browser — no upload needed. Free, private, and secure.`;
  return {
    title: `Convert ${from} to ${to} Online | No Upload Needed | Free Converter`,
    description: desc,
    keywords: `convert ${from.toLowerCase()} to ${to.toLowerCase()} online, free ${from.toLowerCase()} to ${to.toLowerCase()} converter, no upload`,
    creator: "Convifi",
    openGraph: { title: `Convert ${from} to ${to} — No Upload Required`, description: desc, type: "website" },
    twitter: { card: "summary_large_image", title: `Convert ${from} to ${to} in Your Browser`, description: desc },
  };
}

const conversions: Conversion[] = [
  // ── Video ──────────────────────────────────────────────────────────────────
  { from: "MP4",  to: "MKV",  type: "video", metadata: generateMeta("MP4",  "MKV",  "video") },
  { from: "MP4",  to: "AVI",  type: "video", metadata: generateMeta("MP4",  "AVI",  "video") },
  { from: "MP4",  to: "FLV",  type: "video", metadata: generateMeta("MP4",  "FLV",  "video") },
  { from: "MP4",  to: "WEBM", type: "video", metadata: generateMeta("MP4",  "WEBM", "video") },
  { from: "MP4",  to: "MOV",  type: "video", metadata: generateMeta("MP4",  "MOV",  "video") },
  { from: "MP4",  to: "GIF",  type: "video", metadata: generateMeta("MP4",  "GIF",  "video") },
  { from: "MKV",  to: "MP4",  type: "video", metadata: generateMeta("MKV",  "MP4",  "video") },
  { from: "MKV",  to: "AVI",  type: "video", metadata: generateMeta("MKV",  "AVI",  "video") },
  { from: "MKV",  to: "FLV",  type: "video", metadata: generateMeta("MKV",  "FLV",  "video") },
  { from: "MKV",  to: "WEBM", type: "video", metadata: generateMeta("MKV",  "WEBM", "video") },
  { from: "MKV",  to: "MOV",  type: "video", metadata: generateMeta("MKV",  "MOV",  "video") },
  { from: "AVI",  to: "MP4",  type: "video", metadata: generateMeta("AVI",  "MP4",  "video") },
  { from: "AVI",  to: "MKV",  type: "video", metadata: generateMeta("AVI",  "MKV",  "video") },
  { from: "AVI",  to: "FLV",  type: "video", metadata: generateMeta("AVI",  "FLV",  "video") },
  { from: "AVI",  to: "WEBM", type: "video", metadata: generateMeta("AVI",  "WEBM", "video") },
  { from: "AVI",  to: "MOV",  type: "video", metadata: generateMeta("AVI",  "MOV",  "video") },
  { from: "FLV",  to: "MP4",  type: "video", metadata: generateMeta("FLV",  "MP4",  "video") },
  { from: "FLV",  to: "MKV",  type: "video", metadata: generateMeta("FLV",  "MKV",  "video") },
  { from: "FLV",  to: "AVI",  type: "video", metadata: generateMeta("FLV",  "AVI",  "video") },
  { from: "FLV",  to: "WEBM", type: "video", metadata: generateMeta("FLV",  "WEBM", "video") },
  { from: "FLV",  to: "MOV",  type: "video", metadata: generateMeta("FLV",  "MOV",  "video") },
  { from: "WEBM", to: "MP4",  type: "video", metadata: generateMeta("WEBM", "MP4",  "video") },
  { from: "WEBM", to: "MKV",  type: "video", metadata: generateMeta("WEBM", "MKV",  "video") },
  { from: "WEBM", to: "AVI",  type: "video", metadata: generateMeta("WEBM", "AVI",  "video") },
  { from: "WEBM", to: "FLV",  type: "video", metadata: generateMeta("WEBM", "FLV",  "video") },
  { from: "WEBM", to: "MOV",  type: "video", metadata: generateMeta("WEBM", "MOV",  "video") },
  { from: "WEBM", to: "GIF",  type: "video", metadata: generateMeta("WEBM", "GIF",  "video") },
  { from: "MOV",  to: "MP4",  type: "video", metadata: generateMeta("MOV",  "MP4",  "video") },
  { from: "MOV",  to: "MKV",  type: "video", metadata: generateMeta("MOV",  "MKV",  "video") },
  { from: "MOV",  to: "AVI",  type: "video", metadata: generateMeta("MOV",  "AVI",  "video") },
  { from: "MOV",  to: "FLV",  type: "video", metadata: generateMeta("MOV",  "FLV",  "video") },
  { from: "MOV",  to: "WEBM", type: "video", metadata: generateMeta("MOV",  "WEBM", "video") },
  { from: "GIF",  to: "MP4",  type: "video", metadata: generateMeta("GIF",  "MP4",  "video") },
  { from: "GIF",  to: "WEBM", type: "video", metadata: generateMeta("GIF",  "WEBM", "video") },
  // Video → Audio (FFmpeg extracts audio track)
  { from: "MP4",  to: "MP3",  type: "video", metadata: generateMeta("MP4",  "MP3",  "audio") },
  { from: "MP4",  to: "WAV",  type: "video", metadata: generateMeta("MP4",  "WAV",  "audio") },
  { from: "MOV",  to: "MP3",  type: "video", metadata: generateMeta("MOV",  "MP3",  "audio") },
  { from: "MOV",  to: "WAV",  type: "video", metadata: generateMeta("MOV",  "WAV",  "audio") },
  { from: "MKV",  to: "MP3",  type: "video", metadata: generateMeta("MKV",  "MP3",  "audio") },
  { from: "MKV",  to: "WAV",  type: "video", metadata: generateMeta("MKV",  "WAV",  "audio") },
  { from: "WEBM", to: "MP3",  type: "video", metadata: generateMeta("WEBM", "MP3",  "audio") },
  { from: "AVI",  to: "MP3",  type: "video", metadata: generateMeta("AVI",  "MP3",  "audio") },

  // ── Audio ──────────────────────────────────────────────────────────────────
  { from: "MP3",  to: "WAV",  type: "audio", metadata: generateMeta("MP3",  "WAV",  "audio") },
  { from: "MP3",  to: "AAC",  type: "audio", metadata: generateMeta("MP3",  "AAC",  "audio") },
  { from: "MP3",  to: "M4A",  type: "audio", metadata: generateMeta("MP3",  "M4A",  "audio") },
  { from: "MP3",  to: "OGG",  type: "audio", metadata: generateMeta("MP3",  "OGG",  "audio") },
  { from: "MP3",  to: "FLAC", type: "audio", metadata: generateMeta("MP3",  "FLAC", "audio") },
  { from: "WAV",  to: "MP3",  type: "audio", metadata: generateMeta("WAV",  "MP3",  "audio") },
  { from: "WAV",  to: "AAC",  type: "audio", metadata: generateMeta("WAV",  "AAC",  "audio") },
  { from: "WAV",  to: "M4A",  type: "audio", metadata: generateMeta("WAV",  "M4A",  "audio") },
  { from: "WAV",  to: "OGG",  type: "audio", metadata: generateMeta("WAV",  "OGG",  "audio") },
  { from: "WAV",  to: "FLAC", type: "audio", metadata: generateMeta("WAV",  "FLAC", "audio") },
  { from: "AAC",  to: "MP3",  type: "audio", metadata: generateMeta("AAC",  "MP3",  "audio") },
  { from: "AAC",  to: "WAV",  type: "audio", metadata: generateMeta("AAC",  "WAV",  "audio") },
  { from: "AAC",  to: "M4A",  type: "audio", metadata: generateMeta("AAC",  "M4A",  "audio") },
  { from: "M4A",  to: "MP3",  type: "audio", metadata: generateMeta("M4A",  "MP3",  "audio") },
  { from: "M4A",  to: "WAV",  type: "audio", metadata: generateMeta("M4A",  "WAV",  "audio") },
  { from: "M4A",  to: "AAC",  type: "audio", metadata: generateMeta("M4A",  "AAC",  "audio") },
  { from: "FLAC", to: "MP3",  type: "audio", metadata: generateMeta("FLAC", "MP3",  "audio") },
  { from: "FLAC", to: "WAV",  type: "audio", metadata: generateMeta("FLAC", "WAV",  "audio") },
  { from: "FLAC", to: "AAC",  type: "audio", metadata: generateMeta("FLAC", "AAC",  "audio") },
  { from: "FLAC", to: "M4A",  type: "audio", metadata: generateMeta("FLAC", "M4A",  "audio") },
  { from: "OGG",  to: "MP3",  type: "audio", metadata: generateMeta("OGG",  "MP3",  "audio") },
  { from: "OGG",  to: "WAV",  type: "audio", metadata: generateMeta("OGG",  "WAV",  "audio") },
  { from: "OGG",  to: "AAC",  type: "audio", metadata: generateMeta("OGG",  "AAC",  "audio") },

  // ── Image ──────────────────────────────────────────────────────────────────
  { from: "JPEG", to: "PNG",  type: "image", metadata: generateMeta("JPEG", "PNG",  "image") },
  { from: "JPEG", to: "WEBP", type: "image", metadata: generateMeta("JPEG", "WEBP", "image") },
  { from: "JPEG", to: "PDF",  type: "image", metadata: generateMeta("JPEG", "PDF",  "image") },
  { from: "JPEG", to: "BMP",  type: "image", metadata: generateMeta("JPEG", "BMP",  "image") },
  { from: "JPEG", to: "JPG",  type: "image", metadata: generateMeta("JPEG", "JPG",  "image") },
  { from: "PNG",  to: "JPEG", type: "image", metadata: generateMeta("PNG",  "JPEG", "image") },
  { from: "PNG",  to: "WEBP", type: "image", metadata: generateMeta("PNG",  "WEBP", "image") },
  { from: "PNG",  to: "PDF",  type: "image", metadata: generateMeta("PNG",  "PDF",  "image") },
  { from: "PNG",  to: "BMP",  type: "image", metadata: generateMeta("PNG",  "BMP",  "image") },
  { from: "PNG",  to: "TIFF", type: "image", metadata: generateMeta("PNG",  "TIFF", "image") },
  { from: "WEBP", to: "JPEG", type: "image", metadata: generateMeta("WEBP", "JPEG", "image") },
  { from: "WEBP", to: "PNG",  type: "image", metadata: generateMeta("WEBP", "PNG",  "image") },
  { from: "WEBP", to: "PDF",  type: "image", metadata: generateMeta("WEBP", "PDF",  "image") },
  { from: "WEBP", to: "BMP",  type: "image", metadata: generateMeta("WEBP", "BMP",  "image") },
  { from: "WEBP", to: "JPG",  type: "image", metadata: generateMeta("WEBP", "JPG",  "image") },
  { from: "BMP",  to: "PNG",  type: "image", metadata: generateMeta("BMP",  "PNG",  "image") },
  { from: "BMP",  to: "JPEG", type: "image", metadata: generateMeta("BMP",  "JPEG", "image") },
  { from: "BMP",  to: "JPG",  type: "image", metadata: generateMeta("BMP",  "JPG",  "image") },
  { from: "BMP",  to: "WEBP", type: "image", metadata: generateMeta("BMP",  "WEBP", "image") },
  { from: "JPG",  to: "BMP",  type: "image", metadata: generateMeta("JPG",  "BMP",  "image") },
  { from: "JPG",  to: "PDF",  type: "image", metadata: generateMeta("JPG",  "PDF",  "image") },
  { from: "JPG",  to: "JPEG", type: "image", metadata: generateMeta("JPG",  "JPEG", "image") },
  { from: "JPG",  to: "TIFF", type: "image", metadata: generateMeta("JPG",  "TIFF", "image") },
  { from: "SVG",  to: "PNG",  type: "image", metadata: generateMeta("SVG",  "PNG",  "image") },
  { from: "TIFF", to: "JPG",  type: "image", metadata: generateMeta("TIFF", "JPG",  "image") },
  { from: "TIFF", to: "JPEG", type: "image", metadata: generateMeta("TIFF", "JPEG", "image") },
  { from: "TIFF", to: "PNG",  type: "image", metadata: generateMeta("TIFF", "PNG",  "image") },
  { from: "TIFF", to: "WEBP", type: "image", metadata: generateMeta("TIFF", "WEBP", "image") },

  // ── Document (Pandoc WASM) ─────────────────────────────────────────────────
  { from: "markdown",  to: "html",     type: "document", metadata: generateMeta("Markdown",  "HTML",     "document") },
  { from: "markdown",  to: "docx",     type: "document", metadata: generateMeta("Markdown",  "DOCX",     "document") },
  { from: "markdown",  to: "odt",      type: "document", metadata: generateMeta("Markdown",  "ODT",      "document") },
  { from: "markdown",  to: "epub",     type: "document", metadata: generateMeta("Markdown",  "EPUB",     "document") },
  { from: "markdown",  to: "latex",    type: "document", metadata: generateMeta("Markdown",  "LaTeX",    "document") },
  { from: "markdown",  to: "rtf",      type: "document", metadata: generateMeta("Markdown",  "RTF",      "document") },
  { from: "html",      to: "markdown", type: "document", metadata: generateMeta("HTML",      "Markdown", "document") },
  { from: "html",      to: "docx",     type: "document", metadata: generateMeta("HTML",      "DOCX",     "document") },
  { from: "html",      to: "odt",      type: "document", metadata: generateMeta("HTML",      "ODT",      "document") },
  { from: "html",      to: "epub",     type: "document", metadata: generateMeta("HTML",      "EPUB",     "document") },
  { from: "html",      to: "rtf",      type: "document", metadata: generateMeta("HTML",      "RTF",      "document") },
  { from: "docx",      to: "markdown", type: "document", metadata: generateMeta("DOCX",      "Markdown", "document") },
  { from: "docx",      to: "html",     type: "document", metadata: generateMeta("DOCX",      "HTML",     "document") },
  { from: "docx",      to: "odt",      type: "document", metadata: generateMeta("DOCX",      "ODT",      "document") },
  { from: "docx",      to: "epub",     type: "document", metadata: generateMeta("DOCX",      "EPUB",     "document") },
  { from: "docx",      to: "rtf",      type: "document", metadata: generateMeta("DOCX",      "RTF",      "document") },
  { from: "odt",       to: "markdown", type: "document", metadata: generateMeta("ODT",       "Markdown", "document") },
  { from: "odt",       to: "html",     type: "document", metadata: generateMeta("ODT",       "HTML",     "document") },
  { from: "odt",       to: "docx",     type: "document", metadata: generateMeta("ODT",       "DOCX",     "document") },
  { from: "odt",       to: "epub",     type: "document", metadata: generateMeta("ODT",       "EPUB",     "document") },
  { from: "odt",       to: "rtf",      type: "document", metadata: generateMeta("ODT",       "RTF",      "document") },
  { from: "latex",     to: "markdown", type: "document", metadata: generateMeta("LaTeX",     "Markdown", "document") },
  { from: "latex",     to: "html",     type: "document", metadata: generateMeta("LaTeX",     "HTML",     "document") },
  { from: "latex",     to: "docx",     type: "document", metadata: generateMeta("LaTeX",     "DOCX",     "document") },
  { from: "latex",     to: "odt",      type: "document", metadata: generateMeta("LaTeX",     "ODT",      "document") },
  { from: "latex",     to: "epub",     type: "document", metadata: generateMeta("LaTeX",     "EPUB",     "document") },
  { from: "rst",       to: "markdown", type: "document", metadata: generateMeta("RST",       "Markdown", "document") },
  { from: "rst",       to: "html",     type: "document", metadata: generateMeta("RST",       "HTML",     "document") },
  { from: "rst",       to: "docx",     type: "document", metadata: generateMeta("RST",       "DOCX",     "document") },
  { from: "rst",       to: "odt",      type: "document", metadata: generateMeta("RST",       "ODT",      "document") },
  { from: "rst",       to: "epub",     type: "document", metadata: generateMeta("RST",       "EPUB",     "document") },
  { from: "epub",      to: "markdown", type: "document", metadata: generateMeta("EPUB",      "Markdown", "document") },
  { from: "epub",      to: "html",     type: "document", metadata: generateMeta("EPUB",      "HTML",     "document") },
  { from: "epub",      to: "docx",     type: "document", metadata: generateMeta("EPUB",      "DOCX",     "document") },
  { from: "epub",      to: "odt",      type: "document", metadata: generateMeta("EPUB",      "ODT",      "document") },
  { from: "epub",      to: "rtf",      type: "document", metadata: generateMeta("EPUB",      "RTF",      "document") },
  { from: "mediawiki", to: "markdown", type: "document", metadata: generateMeta("MediaWiki", "Markdown", "document") },
  { from: "mediawiki", to: "html",     type: "document", metadata: generateMeta("MediaWiki", "HTML",     "document") },
  { from: "mediawiki", to: "docx",     type: "document", metadata: generateMeta("MediaWiki", "DOCX",     "document") },
  { from: "mediawiki", to: "odt",      type: "document", metadata: generateMeta("MediaWiki", "ODT",      "document") },
  { from: "mediawiki", to: "epub",     type: "document", metadata: generateMeta("MediaWiki", "EPUB",     "document") },
  { from: "org",       to: "markdown", type: "document", metadata: generateMeta("Org Mode",  "Markdown", "document") },
  { from: "org",       to: "html",     type: "document", metadata: generateMeta("Org Mode",  "HTML",     "document") },
  { from: "org",       to: "docx",     type: "document", metadata: generateMeta("Org Mode",  "DOCX",     "document") },
  { from: "org",       to: "odt",      type: "document", metadata: generateMeta("Org Mode",  "ODT",      "document") },
  { from: "org",       to: "epub",     type: "document", metadata: generateMeta("Org Mode",  "EPUB",     "document") },
  { from: "textile",   to: "markdown", type: "document", metadata: generateMeta("Textile",   "Markdown", "document") },
  { from: "textile",   to: "html",     type: "document", metadata: generateMeta("Textile",   "HTML",     "document") },
  { from: "textile",   to: "docx",     type: "document", metadata: generateMeta("Textile",   "DOCX",     "document") },
  { from: "textile",   to: "odt",      type: "document", metadata: generateMeta("Textile",   "ODT",      "document") },
  { from: "textile",   to: "epub",     type: "document", metadata: generateMeta("Textile",   "EPUB",     "document") },
  { from: "ipynb",     to: "html",     type: "document", metadata: generateMeta("Jupyter Notebook", "HTML",     "document") },
  { from: "ipynb",     to: "markdown", type: "document", metadata: generateMeta("Jupyter Notebook", "Markdown", "document") },
  { from: "ipynb",     to: "docx",     type: "document", metadata: generateMeta("Jupyter Notebook", "DOCX",     "document") },
  { from: "ipynb",     to: "rst",      type: "document", metadata: generateMeta("Jupyter Notebook", "RST",      "document") },
];

export { conversions };
