/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as RemoveBgIndexRouteImport } from './routes/remove-bg/index'
import { Route as ReduceImageInKbIndexRouteImport } from './routes/reduce-image-in-kb/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as PassportPhotoIndexRouteImport } from './routes/passport-photo/index'
import { Route as CompressImagesIndexRouteImport } from './routes/compress-images/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ConvertFormatRouteImport } from './routes/convert/$format'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoveBgIndexRoute = RemoveBgIndexRouteImport.update({
  id: '/remove-bg/',
  path: '/remove-bg/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReduceImageInKbIndexRoute = ReduceImageInKbIndexRouteImport.update({
  id: '/reduce-image-in-kb/',
  path: '/reduce-image-in-kb/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportPhotoIndexRoute = PassportPhotoIndexRouteImport.update({
  id: '/passport-photo/',
  path: '/passport-photo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressImagesIndexRoute = CompressImagesIndexRouteImport.update({
  id: '/compress-images/',
  path: '/compress-images/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertFormatRoute = ConvertFormatRouteImport.update({
  id: '/convert/$format',
  path: '/convert/$format',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/convert/$format': typeof ConvertFormatRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/compress-images/': typeof CompressImagesIndexRoute
  '/passport-photo/': typeof PassportPhotoIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/reduce-image-in-kb/': typeof ReduceImageInKbIndexRoute
  '/remove-bg/': typeof RemoveBgIndexRoute
  '/terms/': typeof TermsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/convert/$format': typeof ConvertFormatRoute
  '/about': typeof AboutIndexRoute
  '/blog': typeof BlogIndexRoute
  '/compress-images': typeof CompressImagesIndexRoute
  '/passport-photo': typeof PassportPhotoIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/reduce-image-in-kb': typeof ReduceImageInKbIndexRoute
  '/remove-bg': typeof RemoveBgIndexRoute
  '/terms': typeof TermsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/convert/$format': typeof ConvertFormatRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/compress-images/': typeof CompressImagesIndexRoute
  '/passport-photo/': typeof PassportPhotoIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/reduce-image-in-kb/': typeof ReduceImageInKbIndexRoute
  '/remove-bg/': typeof RemoveBgIndexRoute
  '/terms/': typeof TermsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$slug'
    | '/convert/$format'
    | '/about/'
    | '/blog/'
    | '/compress-images/'
    | '/passport-photo/'
    | '/privacy/'
    | '/reduce-image-in-kb/'
    | '/remove-bg/'
    | '/terms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$slug'
    | '/convert/$format'
    | '/about'
    | '/blog'
    | '/compress-images'
    | '/passport-photo'
    | '/privacy'
    | '/reduce-image-in-kb'
    | '/remove-bg'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/blog/$slug'
    | '/convert/$format'
    | '/about/'
    | '/blog/'
    | '/compress-images/'
    | '/passport-photo/'
    | '/privacy/'
    | '/reduce-image-in-kb/'
    | '/remove-bg/'
    | '/terms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ConvertFormatRoute: typeof ConvertFormatRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CompressImagesIndexRoute: typeof CompressImagesIndexRoute
  PassportPhotoIndexRoute: typeof PassportPhotoIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  ReduceImageInKbIndexRoute: typeof ReduceImageInKbIndexRoute
  RemoveBgIndexRoute: typeof RemoveBgIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remove-bg/': {
      id: '/remove-bg/'
      path: '/remove-bg'
      fullPath: '/remove-bg/'
      preLoaderRoute: typeof RemoveBgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reduce-image-in-kb/': {
      id: '/reduce-image-in-kb/'
      path: '/reduce-image-in-kb'
      fullPath: '/reduce-image-in-kb/'
      preLoaderRoute: typeof ReduceImageInKbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport-photo/': {
      id: '/passport-photo/'
      path: '/passport-photo'
      fullPath: '/passport-photo/'
      preLoaderRoute: typeof PassportPhotoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-images/': {
      id: '/compress-images/'
      path: '/compress-images'
      fullPath: '/compress-images/'
      preLoaderRoute: typeof CompressImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert/$format': {
      id: '/convert/$format'
      path: '/convert/$format'
      fullPath: '/convert/$format'
      preLoaderRoute: typeof ConvertFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogSlugRoute: BlogSlugRoute,
  ConvertFormatRoute: ConvertFormatRoute,
  AboutIndexRoute: AboutIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CompressImagesIndexRoute: CompressImagesIndexRoute,
  PassportPhotoIndexRoute: PassportPhotoIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  ReduceImageInKbIndexRoute: ReduceImageInKbIndexRoute,
  RemoveBgIndexRoute: RemoveBgIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
